### PR TITLE
Support and require pytest>=3.0

### PR DESCRIPTION
**Pull request by nicoddemus**
Hi @tomviner!

I used your plugin to investigate pytest-dev/pytest#2131, this PR makes the plugin work with pytest >= 3.0. I didn't try to keep compatibility with earlier versions, but let me know if you prefer that; is not that hard to keep compatibility.

Cheers,
🍻

### CODE REVIEW

**Comment by tomviner** [comment]
My first outside contribution, exciting! Thanks @nicoddemus :smile:

As a *pytest-dev-assist* tool, I think we should match the versions that pytest itself supports, for bug fixes. But I couldn't find that information on the pytest site. If only there was someone I could ask... 

If bugs are found in pytest 2.x will we release further 2.x patch releases?

**Comment by nicoddemus** [comment]
> My first outside contribution, exciting! Thanks @nicoddemus 😄

That warrants a 🍺 then! 😄 

> As a pytest-dev-assist tool, I think we should match the versions that pytest itself supports, for bug fixes. But I couldn't find that information on the pytest site. If only there was someone I could ask...

As long as I've been a contributor we never did a patch release of a previous minor release. I think it would only happen in an extraordinary circumstance, because we don't have the branches necessary in place for that to happen.

**Comment by tomviner** [comment]
Cheers :beers: :exclamation: 

> As long as I've been a contributor we never did a patch release of a previous minor release. I think it would only happen in an extraordinary circumstance, because we don't have the branches necessary in place for that to happen.

In that case, let's :m: :e-mail: :registered: :nine: :cyclone: and  :shipit: !

**Comment by nicoddemus** [comment]
😆

**Comment by nicoddemus** [comment]
How about a new [pypi release](https://pypi.python.org/pypi/pytest-ast-back-to-python)?

**Comment by tomviner** [comment]
Released https://pypi.python.org/pypi/pytest-ast-back-to-python/1.0.0

In the process of doing that, I noticed the tests break with the latest version of coverage. I've created https://github.com/tomviner/pytest-ast-back-to-python/issues/4 to cover this.

**Comment by nicoddemus** [comment]
Thanks! 😁

**Pull request merged**
